import { Theme } from "@radix-ui/themes";
import type { Metadata } from "next";
import "@radix-ui/themes/styles.css";
export const metadata: Metadata = {
  title: "Webstack | admin",
  description: "Generated by create next app",
};
export default function ({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        <Theme grayColor="mauve" radius="large">
          {children}
        </Theme>
      </body>
    </html>
  );
}
