import type { Metadata } from "next";
import ThemeProvider from "@/src/backend/ui/provider/themeProvider";

export const metadata: Metadata = {
  title: "Webstack | admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
